aplication.name=api-papas-nico

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

supabase.url=${SUPABASE_URL}
supabase.key=${SUPABASE_KEY}
supabase.bucket=fotos

spring.jpa.hibernate.ddl-auto=update

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB