aplication.name=api-papas-nico

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=${PORT:8080}
supabase.url=${SUPABASE_URL}
supabase.key=${SUPABASE_KEY}
supabase.bucket=fotos

spring.jpa.hibernate.ddl-auto=update


spring.datasource.url=jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:6543/postgres?prepareThreshold=0

spring.datasource.username=postgres.kpglivbnlbdxqokyobzu

spring.datasource.password=ZEdXE3pGkzwq2Dbe

spring.datasource.driver-class-name=org.postgresql.Driver

supabase.url=https://kpglivbnlbdxqokyobzu.supabase.co

supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtwZ2xpdmJubGJkeHFva3lvYnp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTEyMTQxNzQsImV4cCI6MjEwNjc5MDE3NH0.U6ISsJsv4WPJeg4UjBy8OIvNU2tyiyiGuwYakQ9ycOk

supabase.bucket=fotos

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB